/** Códigos de erro retornados pelo backend via ProblemDetails.title. */
export const ERROR_CODES = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_INACTIVE: 'USER_INACTIVE',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  PLAYER_ALREADY_EXISTS: 'PLAYER_ALREADY_EXISTS',
  PLAYER_NOT_FOUND: 'PLAYER_NOT_FOUND',
  INVALID_NAME: 'INVALID_NAME',
  POSITION_NOT_FOUND: 'POSITION_NOT_FOUND',
  POSITIONS_LIMIT_EXCEEDED: 'POSITIONS_LIMIT_EXCEEDED',
  DUPLICATE_POSITIONS: 'DUPLICATE_POSITIONS',
  INVALID_POSITION_ID: 'INVALID_POSITION_ID',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
